spring:
  application:
    name: Starter
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://localhost:5433/scalum
    username: scalum
    password: password
    driver-class-name: org.postgresql.Driver
  mail:
    host: localhost
    port: 1025

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: ${keycloak.server-url}/realms/${keycloak.realm}

evolution:
  base-url: http://localhost:8081
  api-key: 429683C4C977415CAAFCCE10F7D57E11

server:
  servlet:
    context-path: '/api'

keycloak:
  realm: latitude
  server-url: https://keycloak.ambience.co.ke
  client-id: aggregator-backend
  client-secret: RzBmZ82b3iWWBiUC9V2QQYHjUiD3mxdo

weaviate:
  host: jzl75dq5g5cjzvahmuzq.c0.europe-west3.gcp.weaviate.cloud
  scheme: http
  http-port: 80
  gprc: grpc-jzl75dq5g5cjzvahmuzq.c0.europe-west3.gcp.weaviate.cloud
  api-key: SHFyQXVMcDVXMlJFVGIvd194Y2FTVG5kZHMyYmg3dFZ5YTVSUW0yaVgrdTYxMlMxMlJFdmd6dE5Dclg0PV92MjAw

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

app:
  webhook-url: https://bikundo.tail8c797b.ts.net/