services:
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025" # SMTP server
      - "8025:8025" # Web UI

  backend:
    image: ghcr.io/allanbikundo/studious-eureka:b2859e7323e3e5ad82f5f2b02892b788e79f2cc9
    ports:
      - 8090:8080
    volumes:
      - ./application.yaml:/app/application.yaml
    environment:
      - SPRING_CONFIG_LOCATION=file:/app/application.yaml
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: scalum
      POSTGRES_USER: scalum
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - prod_postgres_eureka_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  postgres-evolution:
    image: postgres:15
    command: [ "postgres", "-c", "max_connections=1000", "-c", "listen_addresses=*" ]
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=evolution
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - prod_postgres_evolution_data:/var/lib/postgresql/data

  evolution-api:
    image: evoapicloud/evolution-api:v2.3.7
    restart: always
    ports:
      - "8091:8080"
    env_file:
      - evolution.env
    depends_on:
      - postgres-evolution


  redis:
    image: redis:latest
    command: >
      redis-server --port 6379 --appendonly yes
    volumes:
      - prod_evolution_redis:/data
    ports:
      - 6379:6379


volumes:
  prod_postgres_eureka_data:
  prod_postgres_evolution_data:
  prod_evolution_redis:
